### ISSUE TITLE
NameError: name 'e' is not defined

### ISSUE THREAD

**Issue by jbech-linaro** [Linaro/jipdate#29]
After stepping up to Python3, we get an exception with an unknown parameter, like this there is an authentication failure.

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./jipdate.py", line 494, in <module>
    main(sys.argv)
  File "./jipdate.py", line 466, in main
    jira, username = jiralogin.get_jira_instance(cfg.args.t)
  File "/home/jbech/devel/jipdate/jiralogin.py", line 107, in get_jira_instance
    except (JIRAError, e):
NameError: name 'e' is not defined
```

We should take care of the exception in a nicer way. I.e., look at what is really available when getting a [JIRAException](https://jira.readthedocs.io/en/master/api.html?highlight=exception#jiraerror). 

The `e` should be removed, but doing that leads to another error (if CAPTCHA is about to be shown)
```bash
Traceback (most recent call last):
  File "./jipdate.py", line 494, in <module>
    main(sys.argv)
  File "./jipdate.py", line 466, in main
    jira, username = jiralogin.get_jira_instance(cfg.args.t)
  File "/home/jbech/devel/jipdate/jiralogin.py", line 108, in get_jira_instance
    if e.text.find('CAPTCHA_CHALLENGE') != -1:
NameError: name 'e' is not defined
```

**Comment by jbech-linaro** [comment]
Here is one example when it happened to Linus: https://pastebin.linaro.org/view/2af7c9a5
