### ISSUE TITLE
new joiner crash

### ISSUE THREAD

**Issue by thomas-fossati** [Linaro/jipdate#76]
I have installed jipdate on MacOSX (Ventura 13.5.1) using the [instructions](https://jipdate.readthedocs.io/en/latest/install.html#mac-os-v12-monterey-or-later)

I am following the video tutorial and when I do:

```shell
➜ jipdate -q -e
```

I get this error:

```shell
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 11 column 1 (char 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jipdate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jipdate/jipdate.py", line 626, in main
    jira, username = jiralogin.get_jira_instance(cfg.args.t)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jipdate/jiralogin.py", line 119, in get_jira_instance
    j = JIRA(url, basic_auth=(username, password)), username
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jira/client.py", line 580, in __init__
    si = self.server_info()
         ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jira/client.py", line 3120, in server_info
    j = self._get_json("serverInfo")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jira/client.py", line 3858, in _get_json
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/jira/client.py", line 3855, in _get_json
    r_json = json_loads(r)
             ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jira/utils/__init__.py", line 76, in json_loads
    return resp.json()
           ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 11 column 1 (char 10)
```

I have just joined and I don't have JIRA objects yet on my name.   I'm wondering whether that could be the cause?

**Comment by jbech-linaro** [comment]
Hi @thomas-fossati , I believe it could be a missing token. I don't think the installation instructions has been updated to mentioned that. The token in question is the one mentioned here: https://jipdate.readthedocs.io/en/latest/config.html?highlight=token#server . I will send a separate email to you about that.
